=begin
Brian Koser
2010.08.21.15.53
Project Euler - Problem 2
   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   Find the sum of all the even-valued terms in the sequence which do not exceed four million.
=end

sum, a, b = 0, 1, 2

while b < 4000000
   if b % 2 == 0
      sum += b
   end
   
   a, b = b, a + b
end

print "The sum is " + sum.to_s + "\n"